name: CI Test

env:
  main_project_module: app
  playstore_name: Frogobox ID

on:
  pull_request:  # Trigger on every pull request
  workflow_dispatch:  # Allow manual dispatches if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run gradle unit tests
        run: ./gradlew test

      - name: Build gradle project
        run: ./gradlew build

      - name: Run Android instrumentation tests
        uses: emulator-wtf/run-tests@v0.9.10
        with:
          api-token: ${{ secrets.EW_API_TOKEN }}
          app: app/build/outputs/apk/debug/app-debug.apk
          test: app/build/outputs/apk/androidTest/app-debug-androidTest.apk
          outputs-dir: build/test-results

      - name: Publish instrumentation test report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: 'build/test-results/**/*.xml'

      - name: Upload unit test results
        if: always()
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: unit-test-results
          path: app/build/reports/tests/ # Adjust this to your exact path

      - name: Upload Android instrumentation test results
        if: always()
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: android-instrumentation-test-results
          path: app/build/reports/androidTests/ # Adjust this to your exact path
