name: Android CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and run tests
        run: ./gradlew build test connectedAndroidTest

      - name: Upload Unit Test Reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-results
          path: app/build/reports/tests/

      - name: Upload Instrumented Test Reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: android-test-results
          path: app/build/reports/androidTests/
